title = "gitleaks config"

[extend]
useDefault = true

[[allowlists]]
description = "Exclude agent skills"
paths = ['''(\.agents|\.claude)\/skills/.*''']

[[allowlists]]
description = "Exclude monkey patches"
paths = [
  '''(patches\/.+\.patch$)''', # pnpm
]
