title = "gitleaks config"

[extend]
useDefault = true

[[allowlists]]
description = "Exclude agent skills"
paths = [
  '''(\.agents|\.claude)\/skills/.*''', # agent skills
  '''(patches\/.+\.patch$)''', # pnpm patches
]
