directory: ".sushichan044"

tools:
  ghq:
    run: "ghq"
    env:
      GHQ_ROOT: "{{.ToolDir}}"
    description: "ghq wrapper with project-local configuration"

  dir:
    run: "{{.ConfigDir}}/tmpdir.sh"
    description: "Create a temporary directory in the project-local area"
    env:
      BASE_DIR: "{{.ToolDir}}"

  touch:
    run: "{{.ConfigDir}}/touch.sh"
    description: "Create an empty file in the project-local area"
    env:
      BASE_DIR: "{{.ToolDir}}"

aliases:
  gg:
    tool: ghq
    args:
      prepend:
        - get
        - -u
  memo:
    tool: touch
    args:
      prepend:
        - "-e"
        - "md"
