[tools]
python = "3.13.0"
awscli = "2.19.1"
java = "21"
uv = "latest"
go = "1.23.2"
ni = "latest"
bun = "latest"
watchexec = "latest"

[plugins]
ni = "https://github.com/CanRau/asdf-ni.git"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
