#:schema https://mise.jdx.dev/schema/mise.json

[tools]
python = ["3.13.3", "3.12.10", "3.11.12"]
awscli = "2.27.22"
java = "21"
uv = "latest"
go = "1.24.3"
node = "22.16.0"
bun = "latest"
deno = "2.3.3"
tenv = "latest"
watchexec = "latest"
ruby = ["3.4", "3.3"]
"gem:foreman" = "latest"
"npm:@typespec/compiler" = "latest"
"npm:corepack" = "latest"
"npm:git-cz" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

[alias]
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true
idiomatic_version_file_enable_tools = [
    # see: https://github.com/jdx/mise/tree/866ae1ba0c9483357072541dd575203d5034c231/src/plugins/core and search for `idiomatic_file`
    "bun",
    "deno",
    "go",
    "java",
    "node",
    "python",
    "ruby",
    "rust",
    "swift",
    "terraform",
    "zig",
]

[settings.python]
venv_stdlib = true
