[tools]
python = "3.13.2"
awscli = "2.24.15"
java = "21"
uv = "latest"
go = "1.24.0"
node = "22.14.0"
ni = "latest"
bun = "latest"
tenv = "latest"
watchexec = "latest"
ruby = "latest"
"npm:@typespec/compiler" = "latest"
"npm:pnpm" = "latest"

[alias]
ni = "asdf:https://github.com/CanRau/asdf-ni"
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
