#:schema https://mise.jdx.dev/schema/mise.json

[tools]
# When specifying multiple versions, dependabot will only update the first version.

# Languages
python = ["3.13.5", "3.12.10", "3.11.12"]
java = "21"
uv = "latest"
go = "1.24.4"
node = "22.16.0"
bun = "latest"
deno = "2.3.6"
tenv = "latest"
ruby = ["3.4", "3.3"]

# tools
awscli = "2.27.35"
watchexec = "latest"

# tools with Backends
"cargo:cctx" = "latest"
"gem:foreman" = "latest"
"npm:@aku11i/phantom" = "latest"
"npm:@antfu/ni" = "latest"
"npm:@typespec/compiler" = "latest"
"npm:corepack" = "latest"
"npm:every-ts" = "latest"
"npm:git-cz" = "latest"
"npm:npkill" = "latest"
"npm:pnpm" = "latest"
"npm:repomix" = "latest"
"pipx:plamo-translate" = { version = "latest", uvx_args = "--with mlx_lm --with numba --with git+https://github.com/google/sentencepiece.git@2734490#subdirectory=python" }

[alias]
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true
idiomatic_version_file_enable_tools = [
    # see: https://github.com/jdx/mise/tree/866ae1ba0c9483357072541dd575203d5034c231/src/plugins/core and search for `idiomatic_file`
    "bun",
    "deno",
    "go",
    "java",
    "node",
    "python",
    "ruby",
    "rust",
    "swift",
    "terraform",
    "zig",
]

[settings.pipx]
uvx = true

[settings.python]
default_packages_file = "~/.config/mise/.default-python-packages"
venv_stdlib = true
