[tools]
python = "3.12"
awscli = "2.15.41"
java = "21"
uv = "latest"
go = "1.22.3"
node = "20"
yarn = "4"
pnpm = "9"
ni = "latest"

[plugins]
ni = "https://github.com/CanRau/asdf-ni.git"

[settings]
experimental = true
