[tools]
python = "3.12.7"
awscli = "2.18.0"
java = "21"
uv = "latest"
go = "1.23.2"
node = "20.18.0"
yarn = "4"
pnpm = "9"
ni = "latest"
zoxide = "latest"

[plugins]
ni = "https://github.com/CanRau/asdf-ni.git"

[settings]
experimental = true
