[tools]
python = "3.13.0"
awscli = "2.19.4"
java = "21"
uv = "latest"
go = "1.23.3"
ni = "latest"
bun = "latest"
tenv = "latest"
watchexec = "latest"

[plugins]
ni = "https://github.com/CanRau/asdf-ni.git"
tenv = "https://github.com/tofuutils/asdf-tenv.git"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
