[tools]
python = "3.13.2"
awscli = "2.24.24"
java = "21"
uv = "latest"
go = "1.24.1"
node = "22.14.0"
bun = "latest"
tenv = "latest"
watchexec = "latest"
ruby = "latest"
"npm:@typespec/compiler" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "24.0.0"

[alias]
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
