[tools]
python = ["3.13.3", "3.12", "3.13"]
awscli = "2.26.1"
java = "21"
uv = "latest"
go = "1.24.2"
node = "22.14.0"
bun = "latest"
tenv = "latest"
watchexec = "latest"
ruby = ["3.3", "3.4"]
"npm:@typespec/compiler" = "latest"
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "24.0.0"

[alias]
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
