[tools]
python = "3.13.1"
awscli = "2.22.12"
java = "21"
uv = "latest"
go = "1.23.4"
ni = "latest"
bun = "latest"
tenv = "latest"
watchexec = "latest"
ruby = "latest"

[alias]
ni = "asdf:https://github.com/CanRau/asdf-ni"
tenv = "asdf:https://github.com/tofuutils/asdf-tenv"

[settings]
experimental = true

[settings.python]
venv_stdlib = true
