# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal

gui:
  language: 'ja'
  nerdFontsVersion: '3'
git:
  # ref: https://github.com/jesseduffield/lazygit/discussions/2403#discussioncomment-6785560
  overrideGpg: true
  paging:
    colorArg: always
    externalDiffCommand: difft --color=always
    pager: delta --dark --paging=never
