description = "Summarize a given file and export the summary to a new file."
prompt = """
Please provide a concise summary of the following content: {{args}}.

Instructions:
- Write in English unless otherwise specified.
- Save the summary file in the same directory as the input file with "_summary" added to the filename.
"""
