name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

    - name: Get bun store path
      id: bun-store
      shell: bash
      run: echo "store_path=$HOME/.bun-install-cache" >> "$GITHUB_OUTPUT"

    - name: Restore bun cache
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ${{ steps.bun-store.outputs.store_path }}
        key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-store-

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
      env:
        BUN_INSTALL_CACHE_DIR: ${{ steps.bun-store.outputs.store_path }}

    - name: Save bun cache if main branch
      if: github.ref_name == 'main'
      id: save-bun-cache
      uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ${{ steps.bun-store.outputs.store_path }}
        key: ${{ runner.os }}-bun-store-${{ hashFiles('**/bun.lock') }}
