#:schema https://mise.jdx.dev/schema/mise.json

[tools]
"github:anomalyco/opencode" = "1.14.50"
"npm:@ccusage/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@modelcontextprotocol/inspector" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:@vercel/next-browser" = "latest"
"npm:agent-browser" = { version = "latest", postinstall = "agent-browser install" }
"npm:ccusage" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"claude" = "latest"

# Codex repository has too many assets, so we specify the asset pattern to avoid downloading unnecessary assets.
[tools."github:openai/codex"]
version = "latest"
bin = "codex"
[tools."github:openai/codex".platforms]
linux-x64 = { asset_pattern = "codex-x86*.tar.gz" }
macos-arm64 = { asset_pattern = "codex-aarch64*.tar.gz" }

[env]
AGENT_BROWSER_AUTO_CONNECT = "1" # https://github.com/vercel-labs/agent-browser/pull/786
